### ISSUE TITLE
104 lesson is 404 - Not found

### ISSUE THREAD

**Issue by finchren** [antonputra/tutorials#112]
Hello, Anton!

I greatly appreciate your lessons

Lesson 104 "How to Install Prometheus and Grafana on Ubuntu" is not available - https://antonputra.com/monitoring/Install-prometheus-and-grafana-on-ubuntu/

![Screenshot 2022 December 09 11-18](https://user-images.githubusercontent.com/88505337/206656744-cc5d9612-2790-4c6e-839b-64bde93e97c7.png)

https://github.com/antonputra/tutorials/tree/main/lessons/104

**Comment by antonputra** [comment]
Thanks for letting me know, fixed - https://github.com/antonputra/tutorials/pull/114/files
