### ISSUE TITLE
NodeGroup fails to create through terraform

### ISSUE THREAD

**Issue by abourget-cainc** [antonputra/tutorials#117]
Great Tutorials. On [Native EKS Ingress: AWS Load Balancer Controller -112](https://www.youtube.com/watch?v=ZfjpWOC5eoE), I get the following error when deploying the terraform from Lesson 112:

Error: error waiting for EKS Node Group (eks-hackathon:private-nodes) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
	* i-0399217097e46e322, i-09b603f126c569571: NodeCreationFailure: Instances failed to join the kubernetes cluster

I can verify in the AWS console that the NodeGroup is not healthy.  Running the AWSSupport-TroubleshootEKSWorkerNode tool, everything comes back success.

Any ideas?

**Comment by abourget-cainc** [comment]
I solved this by enabling DNS hostnames on the VPC through the AWS dashboard, and re-applying the NodeGroup.  Terraform:

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  enable_dns_hostnames = true

  tags = {
    Name = "main"
  }
}

**Comment by antonputra** [comment]
Thank you! Just updated - https://github.com/antonputra/tutorials/pull/119
