### ISSUE TITLE
Grafana Latency dashboard not working

### ISSUE THREAD

**Issue by aerodiduch** [antonputra/tutorials#131]
Hello, 
I been following your tutorial on how to setup a NGINX-Prometheus-Grafana monitoring system.

Everything is working well until it's time to import the dashboard via json file.

It pops this error.

![image](https://user-images.githubusercontent.com/53284034/214448237-9bb9f349-a07f-4520-b187-01b9b52f045e.png)

Thank you

**Comment by antonputra** [comment]
Most likely, the issue is with "variables". Go to settings and try to update "Data source" to yours.
<img width="848" alt="Screenshot 2023-01-24 at 7 10 42 PM" src="https://user-images.githubusercontent.com/9362325/214471851-4cf0781e-e8cb-4dfe-a209-90d82b78e5cc.png">

**Comment by aerodiduch** [comment]
Thank you so much! Fixed and 100% working. Thank you for your amazing work :)

**Comment by aerodiduch** [comment]
Thank you so much! Fixed and 100% working. Thank you for your amazing work :)
