### ISSUE TITLE
Architecture diagram for lesson 125

### ISSUE THREAD

**Issue by shiningmosquito** [antonputra/tutorials#138]
Hi @antonputra 

I found lesson 125 via search `"terraform eks"` keyword from Google.
It's a good tutorial for beginners studying using terraform to build an EKS cluster.

I made a HIGH-level AWS architecture diagram for lesson 125. 
Are you happy with I create a PR to add this diagram to lesson 125 folder?

![architecture_diagarm_lesson_125](https://user-images.githubusercontent.com/8151846/219317877-25bd6640-87e2-4edc-89d4-ff74e483e13f.png)

**Comment by antonputra** [comment]
Hi @shiningmosquito, sure
