### ISSUE TITLE
Receiving the Error when using Lambda to send alerts to Slack.

### ISSUE THREAD

**Issue by ashit21j** [antonputra/tutorials#139]
Hi Anton,

I am facing a problem with the lambda function; it does not always work.

Most of the time, I receive the below error:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/45489842/220140641-43ad0dcd-1475-4508-baba-33f8cb970807.png">

Can you let me know how to fix this problem?

**Comment by antonputra** [comment]
I think issue here. https://github.com/antonputra/tutorials/blob/main/lessons/122/functions/send-cloudwatch-alarms-to-slack/function.py#L12

Can you find out how the message look like when you get an error(print to console)? Maybe you get an error of some sort.
