### ISSUE TITLE
Is it possible to send an alert from AMP to Microsoft Teams with your lambda code?

### ISSUE THREAD

**Issue by Epic55** [antonputra/tutorials#147]
Hi, is it possible to send an alert from Amazon Prometheus to Microsoft Teams with your lambda code? i used your Slack configuration, but i set Teams url instead of Slack url. When i try to send your example message in lambda, i receive an error. What could be the reason of an error? or maybe i need to change payload message or code in Lambda.
![image](https://user-images.githubusercontent.com/38029225/225558272-02abd5a7-f2a4-414e-ae02-1e9141f3bb28.png)

**Comment by antonputra** [comment]
It should be, you need to check message payload and handle errors appropriately.

**Comment by Epic55** [comment]
Ok thx
