### ISSUE TITLE
"kubernetes.io/cluster/dev-demo" to "kubernetes.io/cluster/staging-demo" at live-infra-v4/staging/vpc/terragrunt.hcl

### ISSUE THREAD

**Issue by yogeshcd** [antonputra/tutorials#161]
Hi Anton,
I was watching you tutorial on youtube and that's great one.
I was wondering in file live-infra-v4/staging/vpc/terragrunt.hcl, do we need to change "kubernetes.io/cluster/dev-demo" to "kubernetes.io/cluster/staging-demo" as the name of EKS cluster will be staging-demo?

Thanks.

**Comment by antonputra** [comment]
Thanks @yogeshcd, yes you need to match the 
`kubernetes.io/cluster/<cluster-name>`, where <cluster-name> is EKS cluster name.
If you find a typo or mistake in the code, can you please create PR. Thanks in advance!
