### ISSUE TITLE
issue with metrics-server from 113 lesson 

### ISSUE THREAD

**Issue by patanjaliv** [antonputra/tutorials#168]
Error: could not download chart: no cached repo found. (try 'helm repo update'): open D:\Users\patha\AppData\Local\Temp\helm\repository\bitnami-index.yaml: The system cannot find the file specified.
│
│   with helm_release.metrics-server,
│   on 9-metrics-server.tf line 13, in resource "helm_release" "metrics-server":
│   13: resource "helm_release" "metrics-server" {
│

**Comment by patanjaliv** [comment]
The metrics-server repo URL has been changed. Please looks into it.,

**Comment by antonputra** [comment]
First try to run
```
helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
helm repo update
helm search repo metrics
...
metrics-server/metrics-server               	3.10.0       	0.6.3      	Metrics Server is a scalable, efficient source ...
```

Still works for me, what's the new url?
