### ISSUE TITLE
Tutorial 102 Doesn't Work with Terraform AWS Provider 5+

### ISSUE THREAD

**Issue by Miracle05** [antonputra/tutorials#177]
```
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.5.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

Terraform doesn't create proper security group for nodes, as result - nodes can't join to cluster

**Comment by Miracle05** [comment]
I just reinstall terraform and everything is working fine. Sorry for disturbing.

**Comment by antonputra** [comment]
> I just reinstall terraform and everything is working fine. Sorry for disturbing.

No worries, let me know if you find any other bugs.
