### ISSUE TITLE
Value defined in disk_size not being reflected

### ISSUE THREAD

**Issue by ranjan0620** [antonputra/tutorials#188]
hi @antonputra I am trying to setup eks cluster by following your tutorial on **how to create eks cluster using terraform module**. I setup the cluster and all and defined the disk_size value to 50. However only 20GB of ebs volume is being created and mounted to root directory. I suppose it should be 50 GB. I am using t3.2xlarge instance type
It would be great if provide some guidance on whats happening or what am i doing wrong.

**Comment by antonputra** [comment]
As far as I remember, you would need to update the template for the nodes.
