### ISSUE TITLE
[info] Lesson 180 - the minio.tf file is empty

### ISSUE THREAD

**Issue by santos-edu** [antonputra/tutorials#201]
cordially notifying, the minio.tf file is empty
https://github.com/antonputra/tutorials/blob/main/lessons/180/terraform/4-minio.tf

thanks for the content

**Comment by antonputra** [comment]
Thanks, @santos-edu, for letting me know. I probably did not commit. At this point, I don't remember all the details for that specific video, so I'll leave it as is and update it in the refresh lesson in the future.
