### ISSUE TITLE
lesson 155 - istio - image error

### ISSUE THREAD

**Issue by barakvbzz** [antonputra/tutorials#217]
hello,

first, thank you for your lessons, they are great.

i ex1, once the image is pulled ok, i describe the pods because it status is "Error":
Back-off restarting failed container first-app in pod first-app-v1-75f898c6bb-xrxjw_staging(266bde88-bce9-4e59-ae2d-df1ce4fa3ca2)

image: aputra/myapp-lesson155:latest

it is also at second app

**Comment by antonputra** [comment]
I remember for old videos I only built images for a specific architecture, ARM (MacBook), and AMD. So, I would suggest building your own image using the source code and Dockerfile in the lesson: 'docker build -t ...'.

<img width="1201" alt="Screenshot 2024-03-21 at 11 22 40 AM" src="https://github.com/antonputra/tutorials/assets/9362325/5cee7153-c350-413b-b92c-c8165d10fdb3">

<img width="1201" alt="Screenshot 2024-03-21 at 11 22 49 AM" src="https://github.com/antonputra/tutorials/assets/9362325/aec9a94b-fe03-4228-bc2f-b7bce2f87c29">
