### ISSUE TITLE
Maybe use compressors for mongodb

### ISSUE THREAD

**Issue by hkupty** [antonputra/tutorials#300]
It might not be significant since the payload is only a single, small object, but for much larger payload sizes it might make a significant difference to use `zlib` or `zstd` [network compressors](https://www.mongodb.com/docs/drivers/go/upcoming/fundamentals/connections/network-compression/) so the payload on the wire between mongo and the server app is smaller. This could be applied to both golang and bun in your previous benchmark.

**Comment by antonputra** [comment]
Thanks, @hkupty. I was thinking about using compression, but since it would be applied to both applications, I decided to leave it out. However, for production use, this would be beneficial. I'll enable compression next time I use MongoDB in the benchmark.
