### ISSUE TITLE
Lesson 162 Part 3: Connection to the database timeouts.

### ISSUE THREAD

**Issue by Brain2life** [antonputra/tutorials#320]
When connecting to the PostgreSQL database deployed from lessons/162/3-part it timeouts.

I've added SG group with inbound rule for PostgreSQL port 5432 and it solved the issue.

Terraform code is missing the part for SG definition.

**Comment by antonputra** [comment]
thanks, @Brain2life. i think i missed it and didn’t test it because the primary goal was to show secrets. if you can, please create a PR; that would be great!

**Comment by Brain2life** [comment]
Hi @antonputra , created PR https://github.com/antonputra/tutorials/pull/340
Please have a look.

**Comment by antonputra** [comment]
Thank you @Brain2life , just merged
