### ISSUE TITLE
running dig *.mydomain.com returns error

### ISSUE THREAD

**Issue by Adebayo120** [antonputra/tutorials#35]
After following the whole process on getting to the spot where i should run dig *.mydomain.com it returning an error, please what do you think could have cause and how do you think i can solve it 
<img width="563" alt="Screenshot 2021-10-27 at 10 34 42" src="https://user-images.githubusercontent.com/54323098/139040031-44bb5806-573a-4815-96ef-3d88bf547e21.png">
r

**Comment by antonputra** [comment]
make sure that your firewall is not blocking port 53 tcp/udp.
