### ISSUE TITLE
Horizontal Scaling not working 

### ISSUE THREAD

**Issue by faheempb** [antonputra/tutorials#45]
Auto-scaling is not working for me on organization level due to that workflow jobs are not running parallelly and taking more time. 
In horizontal-runner-autoscaler.yaml file I defined "organizationNames: MyOrg". and I even tried without this but no luck. 

Please let me know if I'm doing anything wrong here.

Regards,
Faheem

**Comment by antonputra** [comment]
That tutorial was tested for repo-level runners. For the org level, you need to make a few changes (don't forget that you need to update permissions as well)
1. https://github.com/actions-runner-controller/actions-runner-controller#organization-runners
2. https://github.com/actions-runner-controller/actions-runner-controller#deploying-using-github-app-authentication
