### ISSUE TITLE
112 - Error Deploying ALB ingress

### ISSUE THREAD

**Issue by cdesch** [antonputra/tutorials#87]
Great Tutorials. On [Native EKS Ingress: AWS Load Balancer Controller  -112](https://www.youtube.com/watch?v=ZfjpWOC5eoE), I get the following error when deploying the ingress:

```
Error from server (InternalError): error when creating "deployments/canary/ingress.yaml": Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s": context deadline exceeded
```

Any idea why this might be happening?

**Comment by cdesch** [comment]
I believe this solved the issue:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2039#issuecomment-1099032289 
- https://stackoverflow.com/questions/70681534/failed-calling-webhook-vingress-elbv2-k8s-aws

And then [Step 5 in the YAML Tab here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/deploy/installation/)  to get the [IngressClasses](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/ingress_class/)

**Comment by antonputra** [comment]
Should be fixed by enabling DNS, I already updated the code, pls check.
https://github.com/antonputra/tutorials/pull/119
