### ISSUE TITLE
Cretbot sslwith cloudflare as dns

### ISSUE THREAD

**Issue by asterdio-riwaj** [antonputra/tutorials#90]
I followed your tutorial [https://github.com/antonputra/tutorials/tree/main/lessons/078](https://github.com/antonputra/tutorials/tree/main/lessons/078)

Great one, but I used cloudflare as my DNS and came to an issue which caused a redirection loop

This one got resolved by enabling full strict on *ssl/tsl>overview>full strict*

Can I create a pull request to make this tutorial page better and address the issue since cloud flare is widely used dns. 

Here is a reference for you [https://serverfault.com/questions/1109368/cretbot-ssl-certificate-not-working-properly/1109370#1109370](https://serverfault.com/questions/1109368/cretbot-ssl-certificate-not-working-properly/1109370#1109370)

**Comment by antonputra** [comment]
Thanks, merged
